openapi: 3.0.3
info:
  title: Snap Wall API
  description: 活動照片牆 RESTful API 規格
  version: 1.0.0
  contact:
    name: Snap Wall Team

servers:
  - url: https://api.snapwall.example.com
    description: Production API (Cloudflare Workers)
  - url: http://localhost:8787
    description: Local development (Miniflare)

tags:
  - name: Events
    description: 活動管理相關 API
  - name: Photos
    description: 照片相關 API
  - name: Health
    description: 健康檢查 API

paths:
  /health:
    get:
      tags:
        - Health
      summary: 健康檢查
      description: 檢查 API 是否正常運作
      responses:
        '200':
          description: API 正常運作
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: number
                    example: 1700000000000

  /events:
    post:
      tags:
        - Events
      summary: 建立新活動
      description: 主辦方建立新的活動場次
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 100
                  example: "公司尾牙活動"
                driveFolderId:
                  type: string
                  description: Google Drive 資料夾 ID (可選)
                  example: "1a2B3c4D5e6F7g8H9i0J"
      responses:
        '201':
          description: 活動建立成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    $ref: '#/components/schemas/Event'
                  qrCodeUrl:
                    type: string
                    format: uri
                    description: QR Code 圖片 URL
                    example: "https://api.qrserver.com/v1/create-qr-code/?data=https://snapwall.example.com/event/123456"
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /events/{activityId}:
    get:
      tags:
        - Events
      summary: 取得活動資訊
      description: 取得指定活動的詳細資訊
      parameters:
        - $ref: '#/components/parameters/ActivityId'
      responses:
        '200':
          description: 成功取得活動資訊
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    $ref: '#/components/schemas/Event'
                  statistics:
                    $ref: '#/components/schemas/ActivityStatistics'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags:
        - Events
      summary: 結束活動
      description: 主辦方結束活動
      parameters:
        - $ref: '#/components/parameters/ActivityId'
      responses:
        '200':
          description: 活動已結束
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Activity ended successfully"
                  event:
                    $ref: '#/components/schemas/Event'
        '404':
          $ref: '#/components/responses/NotFound'

  /events/{activityId}/photos:
    get:
      tags:
        - Photos
      summary: 取得活動照片列表
      description: 取得指定活動的所有照片
      parameters:
        - $ref: '#/components/parameters/ActivityId'
        - name: limit
          in: query
          description: 每頁照片數量
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          description: 分頁偏移量
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: 成功取得照片列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  photos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Photo'
                  total:
                    type: integer
                    description: 照片總數
                    example: 150
                  hasMore:
                    type: boolean
                    description: 是否還有更多照片
                    example: true
        '404':
          $ref: '#/components/responses/NotFound'

    post:
      tags:
        - Photos
      summary: 新增照片參考
      description: 參與者上傳照片到 Google Drive 後,建立照片參考
      parameters:
        - $ref: '#/components/parameters/ActivityId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - driveFileId
                - thumbnailUrl
                - fullUrl
                - sessionId
              properties:
                driveFileId:
                  type: string
                  description: Google Drive 檔案 ID
                  example: "1a2B3c4D5e6F7g8H9i0J"
                thumbnailUrl:
                  type: string
                  format: uri
                  description: 縮圖 URL
                  example: "https://lh3.googleusercontent.com/..."
                fullUrl:
                  type: string
                  format: uri
                  description: 完整照片 URL
                  example: "https://drive.google.com/uc?id=..."
                sessionId:
                  type: string
                  format: uuid
                  description: 參與者 session ID
                  example: "550e8400-e29b-41d4-a716-446655440000"
                width:
                  type: integer
                  description: 照片寬度 (pixels)
                  example: 1920
                height:
                  type: integer
                  description: 照片高度 (pixels)
                  example: 1080
      responses:
        '201':
          description: 照片參考建立成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  photo:
                    $ref: '#/components/schemas/Photo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'

  /events/{activityId}/ws:
    get:
      tags:
        - Events
      summary: WebSocket 連接升級
      description: 建立 WebSocket 連接以接收即時更新
      parameters:
        - $ref: '#/components/parameters/ActivityId'
        - name: sessionId
          in: query
          required: true
          description: 參與者 session ID
          schema:
            type: string
            format: uuid
      responses:
        '101':
          description: 切換協議到 WebSocket
        '400':
          description: 無效的請求參數
        '404':
          description: 活動不存在

components:
  schemas:
    Event:
      type: object
      required:
        - id
        - createdAt
        - status
        - photoCount
        - participantCount
      properties:
        id:
          type: string
          pattern: '^\d{6}$'
          description: 6 位數字活動代碼
          example: "123456"
        title:
          type: string
          maxLength: 100
          description: 活動標題
          example: "公司尾牙活動"
        createdAt:
          type: number
          description: 建立時間 (Unix timestamp)
          example: 1700000000000
        expiresAt:
          type: number
          description: 過期時間 (Unix timestamp)
          example: 1700086400000
        status:
          type: string
          enum: [active, ended]
          description: 活動狀態
          example: active
        driveFolderId:
          type: string
          description: Google Drive 資料夾 ID
          example: "1a2B3c4D5e6F7g8H9i0J"
        photoCount:
          type: integer
          description: 照片總數
          example: 42
        participantCount:
          type: integer
          description: 參與者總數
          example: 15

    Photo:
      type: object
      required:
        - id
        - activityId
        - sessionId
        - driveFileId
        - thumbnailUrl
        - fullUrl
        - uploadedAt
      properties:
        id:
          type: string
          description: ULID (時間排序)
          example: "01ARZ3NDEKTSV4RRFFQ69G5FAV"
        activityId:
          type: string
          pattern: '^\d{6}$'
          description: 所屬活動 ID
          example: "123456"
        sessionId:
          type: string
          format: uuid
          description: 上傳者 session ID
          example: "550e8400-e29b-41d4-a716-446655440000"
        driveFileId:
          type: string
          description: Google Drive 檔案 ID
          example: "1a2B3c4D5e6F7g8H9i0J"
        thumbnailUrl:
          type: string
          format: uri
          description: 縮圖 URL
          example: "https://lh3.googleusercontent.com/..."
        fullUrl:
          type: string
          format: uri
          description: 完整照片 URL
          example: "https://drive.google.com/uc?id=..."
        uploadedAt:
          type: number
          description: 上傳時間 (Unix timestamp)
          example: 1700000100000
        width:
          type: integer
          description: 照片寬度 (pixels)
          example: 1920
        height:
          type: integer
          description: 照片高度 (pixels)
          example: 1080

    ActivityStatistics:
      type: object
      required:
        - activityId
        - photoCount
        - participantCount
        - activeConnections
        - totalDanmakuSent
      properties:
        activityId:
          type: string
          pattern: '^\d{6}$'
          example: "123456"
        photoCount:
          type: integer
          description: 照片總數
          example: 42
        participantCount:
          type: integer
          description: 參與者總數
          example: 15
        activeConnections:
          type: integer
          description: 當前連接數
          example: 8
        totalDanmakuSent:
          type: integer
          description: 總彈幕數
          example: 127

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: 錯誤類型
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: 錯誤訊息
          example: "Invalid activity ID format"
        details:
          type: object
          description: 額外錯誤詳情
          additionalProperties: true

  parameters:
    ActivityId:
      name: activityId
      in: path
      required: true
      description: 活動 ID (6 位數字)
      schema:
        type: string
        pattern: '^\d{6}$'
      example: "123456"

  responses:
    BadRequest:
      description: 請求參數錯誤
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "VALIDATION_ERROR"
            message: "Invalid request parameters"
            details:
              field: "activityId"
              issue: "Must be a 6-digit number"

    NotFound:
      description: 資源不存在
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "NOT_FOUND"
            message: "Activity not found"

    TooManyRequests:
      description: 請求頻率超過限制
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "RATE_LIMIT_EXCEEDED"
            message: "Photo upload rate limit exceeded"
            details:
              retryAfter: 5000
              limit: "20 photos per 60 seconds"

    InternalError:
      description: 伺服器內部錯誤
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "INTERNAL_ERROR"
            message: "An unexpected error occurred"
